name: Deploy to Easypanel

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Easypanel Deploy Webhook
        run: |
          curl -s -X POST "http://179.199.133.252:3000/api/deploy/a0647d0e65930e2f597c6e828478a89ad225419f092f1e82"
